apiVersion: v1
kind: Service
metadata:
  name: web-app-lb
  namespace: learning-dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use NLB for AWS
spec:
  type: LoadBalancer 
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80