# Application name
spring.application.name=demo

# Server port
server.port=5000

# MongoDB connection settings
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=todo_db
