apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo-api
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 5000        # Cluster-internal port
      targetPort: 5000  # Container port from Deployment
      nodePort: 30081   # External port on Node
